plugins {
	id 'java'
	id 'checkstyle'
	id 'pmd'
	id 'org.springframework.boot' version '4.1.1'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'com.google.protobuf' version '0.9.6'
}

pmd {
	ruleSetFiles = files("${rootProject.projectDir}/config/pmd/ruleset.xml")
	ruleSets = []
}

group = 'com.nuclei'
version = '0.0.1-SNAPSHOT'
description = 'order-service'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

sourceSets {
	main {
		proto {
			srcDir '../protos'
			include 'order/**/*.proto'
		}
	}
}

protobuf {
	protoc {
		artifact = 'com.google.protobuf:protoc:4.31.1'
	}

	plugins {
		grpc {
			artifact = 'io.grpc:protoc-gen-grpc-java:1.75.0'
		}
	}

	generateProtoTasks {
		all().configureEach { task ->
			task.plugins {
				grpc {}
			}
		}
	}
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-grpc-client'
	implementation 'org.springframework.boot:spring-boot-starter-grpc-server'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-security-oauth2-resource-server'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	compileOnly 'org.projectlombok:lombok'
	runtimeOnly 'com.mysql:mysql-connector-j'
	testRuntimeOnly 'com.h2database:h2'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-grpc-client-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-grpc-server-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-security-oauth2-resource-server-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-security-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-validation-test'
	testCompileOnly 'org.projectlombok:lombok'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testAnnotationProcessor 'org.projectlombok:lombok'
}

tasks.named('test') {
	useJUnitPlatform()
}
